message(STATUS "Setup OpenJpeg...")

set(proj OPENJPEG)
SETUP_SUPERBUILD(PROJECT ${proj})

ExternalProject_Add(${proj}
  PREFIX ${proj}
  URL "http://sourceforge.net/projects/openjpeg.mirror/files/2.0.0/openjpeg-2.0.0.tar.gz/download"
  URL_MD5 d9be274bddc0f47f268e484bdcaaa6c5
  BINARY_DIR ${OPENJPEG_SB_BUILD_DIR}
  INSTALL_DIR ${INSTALL_STAGING}
  CMAKE_CACHE_ARGS
    -DCMAKE_INSTALL_PREFIX:STRING=${INSTALL_STAGING}
    -DCMAKE_BUILD_TYPE:STRING=Release
    -DBUILD_CODEC:BOOL=ON
    -DBUILD_DOC:BOOL=OFF
    -DBUILD_JPIP:BOOL=OFF
    -DBUILD_JPWL:BOOL=OFF
    -DBUILD_MJ2:BOOL=OFF
    -DBUILD_PKGCONFIG_FILES:BOOL=ON
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DBUILD_TESTING:BOOL=OFF
    -DBUILD_THIRDPARTY:BOOL=OFF
    -DCMAKE_PREFIX_PATH:STRING=${INSTALL_STAGING};${CMAKE_PREFIX_PATH}
    ${OPENJPEG_SB_CONFIG}
  DEPENDS ""
  CMAKE_COMMAND ${SB_CMAKE_COMMAND}
  )

